$: << File.expand_path(File.dirname(__FILE__))
require 'ttt'
require 'ttt_config'
require 'board'
require 'game'
require 'hash_cache'
require 'mongo_cache'
require 'nil_cache'
require 'player'
require 'score_board'
